import 'dart:math';

import '../../audio/sentence_buffer.dart';
import '../../core/llm/llm_router.dart';
import '../../core/llm/llm_provider.dart';
import '../../models/age_band.dart';
import '../../models/skill.dart';
import '../activity_base.dart';
import '../s02_creativity/what_if_machine.dart' show SpeakSentenceCallback;

/// Sleep Stories: calming bedtime stories generated by the LLM.
///
/// Teaches: relaxation, imagination, calm focus, bedtime routine.
///
/// Flow:
/// 1. Bot asks if the child is ready for a bedtime story.
/// 2. Bot generates and tells a gentle, calming story.
/// 3. Story uses peaceful imagery: moonlight, gentle waves, warm blankets.
/// 4. Story ends with the character falling peacefully asleep.
/// 5. One story per session, about 3-4 minutes.
class SleepStories extends Activity {
  final LlmRouter _llmRouter;
  final SentenceBuffer _sentenceBuffer;
  SpeakSentenceCallback? onSpeakSentence;

  final Random _rng = Random();

  bool _active = false;
  int _score = 0;

  /// 0=intro, 1=story told, 2=done
  int _phase = 0;

  static const List<String> _storyThemes = [
    'a little bear who finds a cozy cave by a gentle river',
    'a baby cloud floating slowly across the moonlit sky',
    'a tiny fish swimming through a peaceful underwater garden',
    'a kitten curling up in a warm blanket on a rainy night',
    'a little star that twinkles and watches over sleeping children',
    'a butterfly resting on a soft flower in a quiet meadow',
    'a baby bird nestled in a warm nest high in a gentle tree',
    'a small boat floating on a calm lake under the moonlight',
    'a sleepy owl perched on a branch under a blanket of stars',
    'a bunny hopping through a field of soft dandelions at sunset',
  ];

  SleepStories({
    required LlmRouter llmRouter,
    SentenceBuffer? sentenceBuffer,
    this.onSpeakSentence,
  })  : _llmRouter = llmRouter,
        _sentenceBuffer = sentenceBuffer ?? SentenceBuffer();

  @override
  String get id => 'health_sleep_stories';

  @override
  String get name => 'Sleep Stories';

  @override
  String get category => 'wellness';

  @override
  String get description =>
      'Calming bedtime stories to help you drift off to peaceful sleep.';

  @override
  List<String> get skills => [
        'relaxation',
        'imagination',
        'calm focus',
        'bedtime routine',
      ];

  @override
  int get minAge => 3;

  @override
  int get maxAge => 8;

  @override
  SkillId? get skillId => SkillId.healthWellness;

  @override
  Map<String, List<String>> get voiceTriggers => const {
        'en': [
          'bedtime story',
          'sleep story',
          'tell me a story for bed',
          'sleepy story',
          'goodnight story',
          'calm story',
        ],
        'hi': [
          'सोने की कहानी',
          'शुभ रात्रि कहानी',
          'नींद की कहानी',
        ],
        'te': [
          'నిద్ర కథ',
          'పడుకునే కథ',
          'శుభ రాత్రి కథ',
        ],
      };

  @override
  AgeBand get targetAgeBand => AgeBand.nursery;

  @override
  bool get isActive => _active;

  @override
  String get progressSummary {
    return _phase >= 1 ? 'Story complete. Score: $_score points.' : 'Story in progress.';
  }

  @override
  Future<String> start() async {
    _active = true;
    _score = 0;
    _phase = 0;

    return 'It is bedtime story time. Get comfortable, snuggle up with your '
        'blanket, and close your eyes if you like. I have a gentle story for '
        'you tonight. Are you ready to listen?';
  }

  @override
  Future<String?> processResponse(String childSaid) async {
    if (!_active) return null;
    final lower = childSaid.toLowerCase().trim();

    if (_containsQuit(lower)) {
      return await end();
    }

    switch (_phase) {
      case 0:
        _phase = 1;
        return await _generateStory();

      case 1:
        _phase = 2;
        _active = false;
        _score += 10;
        return 'Sweet dreams, little one. Close your eyes and drift away '
            'to a peaceful sleep. Goodnight.';

      default:
        return await end();
    }
  }

  @override
  Future<String> end() async {
    _active = false;
    return 'Sweet dreams. I will be here whenever you want another '
        'bedtime story. Goodnight.';
  }

  Future<String> _generateStory() async {
    final theme = _storyThemes[_rng.nextInt(_storyThemes.length)];

    final systemPrompt = 'You are a gentle bedtime storyteller for a child aged 3-8. '
        'Tell a very calm, soothing bedtime story about $theme. '
        'Rules: '
        '1. Use peaceful imagery: soft moonlight, gentle waves, warm blankets, '
        'quiet forests, twinkling stars, calm rivers. '
        '2. Speak slowly and gently, using short simple sentences. '
        '3. Include sensory details: soft fur, warm glow, cool breeze, '
        'quiet whispers, sweet scent of flowers. '
        '4. The story should have a very calm arc. No danger, no conflict. '
        'Just a gentle journey that ends with the character falling '
        'peacefully asleep. '
        '5. End the story with the character curling up, closing their eyes, '
        'and drifting off to sleep. '
        '6. The story should be about 200-250 words. '
        '7. No markdown, no bullets. Pure spoken narrative. '
        '8. Do not ask any questions. Just tell the story.';

    final messages = <Map<String, String>>[
      {'role': 'system', 'content': systemPrompt},
      {'role': 'user', 'content': 'Tell me a bedtime story please.'},
    ];

    try {
      final provider = _llmRouter.getProvider();
      String response;

      if (onSpeakSentence != null) {
        response = await _streamWithTts(provider, messages);
      } else {
        final buffer = StringBuffer();
        await for (final token in provider.stream(messages)) {
          buffer.write(token);
        }
        response = buffer.toString().trim();
      }

      _score += 30;
      return response.isNotEmpty ? response : _fallbackStory();
    } catch (e) {
      _score += 15;
      return _fallbackStory();
    }
  }

  Future<String> _streamWithTts(
    LlmProvider provider,
    List<Map<String, String>> messages,
  ) async {
    _sentenceBuffer.reset();
    final fullResponse = <String>[];

    try {
      await for (final token in provider.stream(messages)) {
        final sentence = _sentenceBuffer.feed(token);
        if (sentence != null) {
          fullResponse.add(sentence);
          await onSpeakSentence!(sentence);
        }
      }
      final remaining = _sentenceBuffer.flush();
      if (remaining != null) {
        fullResponse.add(remaining);
        await onSpeakSentence!(remaining);
      }
      return fullResponse.join(' ');
    } catch (e) {
      if (fullResponse.isNotEmpty) return fullResponse.join(' ');
      return _fallbackStory();
    }
  }

  String _fallbackStory() {
    return 'Once upon a time, in a quiet forest under the soft moonlight, '
        'there lived a little bear. The little bear had the softest fur, '
        'as warm as a cozy blanket. Every evening, the bear would walk '
        'along a gentle stream, listening to the water sing a quiet lullaby. '
        'The fireflies would light up the path with their tiny golden glow. '
        'Tonight, the bear found a perfect spot under an old oak tree. '
        'The leaves rustled softly in the cool breeze, whispering goodnight. '
        'The bear curled up on a bed of soft moss, tucked its nose under its '
        'paw, and watched the stars twinkle one by one. '
        'The moon smiled down gently, wrapping the forest in silver light. '
        'The stream hummed its lullaby, the crickets played their gentle song, '
        'and the little bear closed its eyes. '
        'Slowly, peacefully, the bear drifted off to the most wonderful '
        'dream, where flowers bloomed in every color and butterflies danced '
        'on the warm breeze. And everything was calm, and everything was good.';
  }

  bool _containsQuit(String text) {
    const quitWords = ['quit', 'exit', 'stop', 'done', 'finish'];
    for (final w in quitWords) {
      if (text.contains(w)) return true;
    }
    return false;
  }
}
